<a href="https://colab.research.google.com/github/chandankr2878/chandan-colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l=[1,2,3]
print(l)
arr=np.array(l)
print(arr)

[1, 2, 3]
[1 2 3]


In [ ]:
import numpy as np
# arrary 1d
arr = np.zeros(5)       #000000
print(arr)

# 2d
arr1 = np.zeros((2,3))+8 # 2 row and 3 cols
print(arr1)

[0. 0. 0. 0. 0.]
[[8. 8. 8.]
 [8. 8. 8.]]


In [ ]:

# ones
import numpy as np
# array 1d
arr = np.ones(5)
print(arr)

# 2d
arr1 = np.ones((2,3))+77
print(arr1)

[1. 1. 1. 1. 1.]
[[78. 78. 78.]
 [78. 78. 78.]]


In [ ]:
# full
import numpy as np
# array 1d
arr = np.full((5),7)
print(arr)

# 2d
arr1 = np.full((2,3),7+1)
print(arr1)

[7 7 7 7 7]
[[8 8 8]
 [8 8 8]]


In [ ]:
import numpy as np
arr = np.zeros(5)
print(arr)
print(arr.shape) # 5
print(arr.ndim) # 1d
print(arr.size) # 5
print(arr.dtype) # float

# 2d
print("2d ones start")
arr1 = np.zeros((3,2))
print(arr1)
print(arr1.shape) # 3,2
print(arr1.ndim) # 2d
print(arr1.size) # 6
print(arr1.dtype) # float

[0. 0. 0. 0. 0.]
(5,)
1
5
float64
2d ones start
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


In [ ]:
# 1d array arange
import numpy as np
arr = np.arange(6)
print(arr)

# 2d
arr1 = arr.reshape(2,3) # 2 rows and 3 cols
print(arr1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
# flatten | copy
import numpy as np
# 2d
arr = np.arange(6)
arr1 = arr.reshape(2,3)
print(arr1)
# flatten
arr_new = arr1.flatten()
arr_new[0] = 100
print(arr1)
print(arr_new)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[100   1   2   3   4   5]


In [ ]:
# ravel | original
import numpy as np
# 2d
arr = np.arange(6).reshape(2,3)
print(arr)
# ravel
arr_new1 = arr.ravel()
arr_new1[0] = 200
print(arr)
print(arr_new1)


[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]
[200   1   2   3   4   5]


In [ ]:
# transpose
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

# transpose
arr1 = arr.transpose()
print(arr1)

#
arr1 = arr.T
print(arr1)

In [ ]:
# numpy array operations
# 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4])#slicing
print(arr[-1])
print(arr[::])
print(arr[0:4:2])
print(arr[::2])# jump by 1 start from zero to end element
print(arr[::-1]) # for reverse

print(arr[:-3:-1])#########

3
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[5 4]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
# print(arr)
# print(arr[0:2])
# print(arr[:,0])# all rows
print(arr[0,0])#row-1,column-1
print(arr[0,1])
print(arr[1,2])
print(arr[1,1])
print(arr[[0,1],[1,0]])
print(arr[[0,0],[1,1]])


1
2
6
5
[2 4]
[2 2]


In [ ]:
# Loop in numpy
# 1d
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
for i in arr:
    print(i)
# 2d
for i in arr:
  print(i)

[10 20 30 40]
10
20
30
40
10
20
30
40


In [ ]:


import numpy as np
arr=np.array([[10,20],[30,40],[50,60]])
print(arr)
print(arr[[0,1,2],[1,1,0]])

import numpy as np
arr=np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],[7526,86,637236],[9528,45,428760],[10788,17,183396]])
print(arr)
print(arr[[0,0],[0,1]])
print(arr[0,0:2])\

# 3d
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.ndim)
print(arr[0])
print(arr[0,0])
print(arr[0,0,0])
print(arr[:,0])
print(arr[:,:,1])


#  loop
import numpy as np
arr=np.array([10,20,30,40])
print(arr.ndim)
print(arr)
for i in arr:
    print(i)


import numpy as np
arr=np.array([[10,20],[30,40]])
print(arr)
for i in arr:
  for j in i:
    print(j)

for i in np.flatter(arr):
   print(arr)


import numpy as np
arr=np.array([10,60,49,99,28,33])
# print(arr)
# print(np.sort(arr))
# print(np.sort(arr)[::-1])


#2d
arr1=arr.reshape(3,2)
print(arr1)
print(np.sort(arr1,axis=0))


# filter 1d
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0:3])
print(arr[arr>30])

#where
import numpy as np
arr=np.array([10,20,30,40])
print(np.where(arr>20,"true","false"))

print(np.where(arr>20,arr * 2,arr))

[[10 20]
 [30 40]
 [50 60]]
[20 40 50]
[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]
 [  7526     86 637236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[2453   75]
[2453   75]
3
[[1 2]
 [3 4]]
[1 2]
1
[[1 2]
 [5 6]]
[[2 4]
 [6 8]]
1
[10 20 30 40]
10
20
30
40
[[10 20]
 [30 40]]
10
20
30
40


AttributeError: module 'numpy' has no attribute 'flatter'

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70])
# # Print 30
# # Print 70 using negative indexing
# # Print [20 30 40]
# # Print [10 30 50 70]
# # Reverse the array

print(arr[2:3])
print(arr[-1])
print(arr[1:4])
print(arr[0:7:2])
print(arr[::-1])






import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# # Print 5
# # Print first row
# # Print last row
# # Print first column
# # Print last column

print(arr[[1,1]])
print(arr[1,1])

print(arr[0])
print(arr[2])

print(arr[:,0])
print(arr[:,2])
print(arr[-1])
print(arr[-2])
print(arr[:,1])



import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[2,1])      # ?
print(arr[-1,-2])    # ?
print(arr[:,2])      # ?
print(arr[0:2,1:3])  # ?????????????????????????????????????????????????????????????????????????
print(arr[1:,1:])    # ???????????????


#reshaping
import numpy as np
arr=np.array([1,4,6,7,2,3,])
arr1=arr.reshape(3,2)
print(arr1)

[30]
70
[20 30 40]
[10 30 50 70]
[70 60 50 40 30 20 10]
[[4 5 6]
 [4 5 6]]
5
[1 2 3]
[7 8 9]
[1 4 7]
[3 6 9]
[7 8 9]
[4 5 6]
[2 5 8]
8
8
[3 6 9]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]
[[1 4]
 [6 7]
 [2 3]]
